# Created with YamlCreate.ps1 v2.2.3 $debug=QUSU.CRLF.5-1-22621-963.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: AgileBits.1Password
PackageVersion: 8.10.1
PackageLocale: en-US
Publisher: Agilebits Inc.
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: 1Password
PackageUrl: https://1password.com/downloads/windows/
License: Trialware
# LicenseUrl:
Copyright: Copyright © 2022 AgileBits, Inc.
# CopyrightUrl:
ShortDescription: 1Password remembers all your passwords for you, and keeps them safe and secure behind the one password that only you know.
# Description:
# Moniker:
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
